fix error thrown by npm test in circle-ci build
test.js was throwing an error “Error: Cannot find module 'server”. removed the require statement causing this. shouldn’t have been there in the first place.

ran locally and is no longer throwing error.